### ISSUE TITLE
Partial Incompatibility with Ember 2.10

### ISSUE THREAD

**Issue by alexlafroscia** [ciena-blueplanet/ember-block-slots#43] opened 2016-12-07 23:03 UTC
@thoov and I came across a case where `ember-block-slots` is not compatible with Ember 2.10.0.  It seems that yielding a set of arguments to a block slot through `block-params`, when once of those params is a `hash`, causes the following issue on browsers that do not have a native `WeakMap` implementation (yeah, it took a while to get to the bottom of this 😉 )

> TypeError: Attempting to define property on object that is not extensible.

I created a demo repo [here](https://github.com/alexlafroscia/__demo-broken-block-slots) that reproduces the issue.  Basically, run the tests in Phantom and you'll see a failure, but in Chrome you will not.  Just running `ember test` will show a message that isn't helpful, an error about an assertion that is just a symptom of the real problem.  If you do `ember test --serve` you'll see both that error, plus an additional message about the "real" one.

**Output from `ember test`**

<img width="1050" alt="screen shot 2016-12-07 at 2 51 27 pm" src="https://cloud.githubusercontent.com/assets/1645881/20990531/243f63d8-bc8e-11e6-89bb-21ae5ff34e68.png">

**Output from `ember test --serve`**

<img width="638" alt="screen shot 2016-12-07 at 3 02 21 pm" src="https://cloud.githubusercontent.com/assets/1645881/20990557/3ca2f520-bc8e-11e6-8b91-4cf907b79d59.png">

**Comment by jasonmit** [comment] 2016-12-08 01:38
https://github.com/ciena-blueplanet/ember-block-slots/blob/master/addon/helpers/block-params.js#L27-L31 is likely the cause

Introduced by https://github.com/emberjs/ember.js/pull/14244

**Comment by sglanzer-fire** [comment] 2016-12-08 14:33
Awesome root cause analysis and thanks a ton for the PR!

**Comment by sglanzer-fire** [comment] 2016-12-08 14:39
Closed via #44

**Closed as completed by sglanzer-fire** 2016-12-08 14:39 UTC
